name: Scrape CS2 Ladderboard Statistics

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '56 3 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape
          git config user.name CS Stats Bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[BOT] Update CS2 Elo database"
          git push origin main