name: Scrape CS2 Ladderboard Statistics

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '@weekly'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install
      - run: |
          npm run scrape
          git config --global user.email "bot@example.com"
          git config --global user.name "CS Stats Bot"
          git diff --quiet && git diff --staged --quiet || git commit -am "[BOT] Update CS2 Elo database"
          git push origin main